host:                mail.tldpanel.com           # required
port:                587                         # optional - default 25
starttls:            true                        # <true|false> - default false
allow-insecure:      false                       # <true|false> - default false
auth:                plain                       # <none|plain|login|cram-md5> - default none
username:            smtp@gold-dev.com           # required for plain, login and cram-md5 auth
password:            yUpOWd9OrmlRceyi            # required for plain & login auth
# secret:              <cram-secret>               # required for cram-md5 auth
# return-path:         <bounce-address>            # optional - overrides Return-Path for all released emails
# recipient-allowlist: '@example\.com$'            # optional - regex to limit allowed relay addresses or domains (see below)
